// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIHcnrmR3TKCR_z3aKW3Q_tYaCCwiKR4',
    appId: '1:702507634085:web:6d128e985b642260f8ac4c',
    messagingSenderId: '702507634085',
    projectId: 'face-book-login-b3a70',
    authDomain: 'face-book-login-b3a70.firebaseapp.com',
    databaseURL: 'https://face-book-login-b3a70-default-rtdb.firebaseio.com',
    storageBucket: 'face-book-login-b3a70.appspot.com',
    measurementId: 'G-S3ZD4QQF1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTj5zTOW4HbFOG1cywkXvBeu-XpcZJyRc',
    appId: '1:702507634085:android:fc23181f636b079ff8ac4c',
    messagingSenderId: '702507634085',
    projectId: 'face-book-login-b3a70',
    databaseURL: 'https://face-book-login-b3a70-default-rtdb.firebaseio.com',
    storageBucket: 'face-book-login-b3a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZPI6Hq-xdV4msE5JZTPHKs18bZBoCb0',
    appId: '1:702507634085:ios:fb27588ada25b65af8ac4c',
    messagingSenderId: '702507634085',
    projectId: 'face-book-login-b3a70',
    databaseURL: 'https://face-book-login-b3a70-default-rtdb.firebaseio.com',
    storageBucket: 'face-book-login-b3a70.appspot.com',
    iosClientId: '702507634085-26fugts3egargpq4khkmegs9t0ohihu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKZPI6Hq-xdV4msE5JZTPHKs18bZBoCb0',
    appId: '1:702507634085:ios:fb27588ada25b65af8ac4c',
    messagingSenderId: '702507634085',
    projectId: 'face-book-login-b3a70',
    databaseURL: 'https://face-book-login-b3a70-default-rtdb.firebaseio.com',
    storageBucket: 'face-book-login-b3a70.appspot.com',
    iosClientId: '702507634085-26fugts3egargpq4khkmegs9t0ohihu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookLogin',
  );
}
